about = "Dracula is believed to be in the United States public domain; that is, it is believed to be free of copyright restrictions in the United States."
logo = "bat.png"
name = "Dracula (AO3Mimic)"
single_work = true
