about = "The works on this site are believed to be in the United States public domain; that is, they are believed to be free of copyright restrictions in the United States."
name = "AO3Mimic Demonstration Site"
