notes = "<p>For a complete list of the books in the Fantasy Masterworks series, see <a href=\"https://en.wikipedia.org/wiki/Fantasy_Masterworks\">Wikipedia</a>.</p>"
summary = "<p>Fantasy Masterworks is a series of British paperbacks by Millennium (an imprint of Victor Gollancz). It is intended to comprise “some of the greatest, most original, and most influential fantasy ever written” and to contain “the books which, along with Tolkien, Peake and others, shaped modern fantasy.”</p>"
title = "Fantasy Masterworks"
works = ["elfland"]
