summary = "<p>Sherlock Holmes is a fictional detective created by British author Arthur Conan Doyle. Referring to himself as a “consulting detective” in his stories, Holmes is known for his proficiency with observation, deduction, forensic science and logical reasoning that borders on the fantastic, which he employs when investigating cases for a wide variety of clients, including Scotland Yard.</p>"
title = "Sherlock Holmes"
works = [
  "a-scandal-in-bohemia",
  "the-redheaded-league",
  "the-adventure-of-the-blue-carbuncle",
  "the-adventure-of-the-speckled-band",
  "the-adventure-of-the-dancing-men",
]
