additional_tags = [
  [
    "Snakes",
    "https://archiveofourown.org/tags/Snakes",
  ],
  [
    "Period-Typical Racism",
    "https://archiveofourown.org/tags/Period-Typical%20Racism",
  ],
]
author = "Sir Arthur Conan Doyle"
categories = [
  "Gen",
]
characters = [
  [
    "Sherlock Holmes",
    "https://archiveofourown.org/tags/Sherlock%20Holmes",
  ],
  [
    "John Watson",
    "https://archiveofourown.org/tags/John%20Watson",
  ],
]
collections = []
display_chapter_numbers = false
fandoms = [
  [
    "Sherlock Holmes - Arthur Conan Doyle",
    "https://archiveofourown.org/tags/Sherlock%20Holmes%20-%20Arthur%20Conan%20Doyle",
  ],
]
is_complete = true
ordering = 3
pubdate = 1892-02-01
pubdate_granularity = "MONTH"
rating = "Not Rated"
relationships = [
  [
    "Sherlock Holmes & John Watson",
    "https://archiveofourown.org/tags/Sherlock%20Holmes%20*a*%20John%20Watson",
  ],
]
summary = "<p>Holmes assists a young woman whose sister has recently died.</p>"
title = "The Adventure of the Speckled Band"
warnings = [
  "No Archive Warnings Apply",
]

[[chapters]]
content_file = "the-adventure-of-the-speckled-band.html"
interstitial = false
title = "Oneshot"
